### ISSUE TITLE
Babel errors when files to transpile not in certain location

### ISSUE THREAD

**Issue by bardware** [gkatsev/babel-plugin-inline-json#3]
I asked this question on [stackoverflow](http://stackoverflow.com/questions/41070789/babel-errors-when-files-to-transpile-not-in-certain-location/41071629) but got no answer.

I took the ES6-js files from videojs and copied them to a certain location in my project. When I call `browserify dev/videojs/js/video.js -o bundle.js -t [ babelify ]` from the root of my project where `package.json` resides I get the following error:

```
Error: D:/Webs/videojs/dev/videojs/js/video.js: Cannot find module '../../package.json' from 'D:\Webs\videojs\dev\videojs\js'
    at Function.module.exports [as sync] (D:\Webs\videojs\node_modules\resolve\lib\sync.js:33:11)
    at PluginPass.MemberExpression (D:\Webs\videojs\node_modules\babel-plugin-inline-json\lib\index.js:27:45)
    at newFn (D:\Webs\videojs\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (D:\Webs\videojs\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (D:\Webs\videojs\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (D:\Webs\videojs\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (D:\Webs\videojs\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\Webs\videojs\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\Webs\videojs\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\Webs\videojs\node_modules\babel-traverse\lib\index.js:114:17)
```

When I move the files one folder up and invoke `browserify babelify` everything works. Does it have to do with your code?

**Comment by bardware** [comment]
I finally went through the video.js code line by line and stumbled upon `videojs.VERSION = require('../../package.json').version;`
Sorry to bother!
